services:
  opcua-server:
    build: https://github.com/monash-automation/mes-opcua-server.git
    container_name: mes-opcua-server
    ports:
      - "4840:4840"
    environment:
      - OPCUA_SERVER_URL=opc.tcp://0.0.0.0:4840
      - OPCUA_SERVER_NAME="Monash Automation OPC UA Server"
      - OPCUA_SERVER_NAMESPACE=http://monashautomation.com/opcua-server
      - OPCUA_SERVER_REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    restart: unless-stopped
  redis:
    image: "redis:alpine"
    container_name: mes-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
  printing-server:
    build: https://github.com/monash-automation/mes-printing-server.git
    container_name: mes-printing-server
    ports:
      - "8000:8000"
    volumes:
      - ./gcode-files:/var/lib/mes/gcode-files
    environment:
      - UPLOAD_PATH=/var/lib/mes/gcode-files
      - DATABASE_URL=postgresql+asyncpg://mes:mes@db:5432/mes
      - OPCUA_SERVER_URL=opc.tcp://opcua-server:4840
      - OPCUA_SERVER_NAMESPACE=http://monashautomation.com/opcua-server
      - AUTO_SCHEDULE=false
      - MOCK_PRINTER_JOB_TIME=10
      - MOCK_PRINTER_TARGET_BED_TEMPERATURE=50
      - MOCK_PRINTER_TARGET_BED_NOZZLE=60
      - LOGGING_LEVEL=ERROR
    restart: unless-stopped
    depends_on:
      - opcua-server
  printing-service:
    build: https://github.com/monash-automation/mes-printing-service.git
    container_name: mes-printing-service
    ports:
      - "3001:5173"
    environment:
      # Must use fixed IP if not using a reverse proxy
      - VITE_PRINTER_SERVER_URL=http://172.32.1.188:8000
      - VITE_AUTH0_DOMAIN=dev-qmgetaxjc1xzy0s7.us.auth0.com
      - VITE_AUTH0_CLIENT_ID=sS0NnS6ieRLLVj1NEKdEkuxfoGmTaaOZ
      - VITE_AUTH0_AUDIENCE=https://dev-qmgetaxjc1xzy0s7.us.auth0.com/api/v2/
    restart: unless-stopped
    depends_on:
      - printing-server
  db:
    image: postgres:16
    container_name: mes-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=mes
      - POSTGRES_PASSWORD=mes
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    shm_size: 128mb
    restart: unless-stopped
  grafana:
    image: grafana/grafana-oss
    container_name: mes-grafana
    user: MY_USER_ID
    ports:
      - "3000:3000"
    environment:
      - GF_LOG_LEVEL=error
      - GF_PANELS_DISABLE_SANITIZE_HTML=true
      - "GF_INSTALL_PLUGINS=grafana-clock-panel, grafana-simple-json-datasource, redis-datasource, marcusolsson-dynamictext-panel"
    volumes:
      - ./grafana-storage:/var/lib/grafana
    restart: always